version: "3"

services:
  web:
    container_name: portfolio-website
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_GA_TRACKING_ID: ${VITE_GA_TRACKING_ID}
    ports:
      - "80:80"
