name: Docker Build and Publish

on:
  release:
    types:
      - created

jobs:
  portfolio-website:
    uses: tylerpitcher/ci-cd/.github/workflows/build.yaml@main
    with:
      dockerfile_path: ./Dockerfile
      image_name: portfolio-website
      image_version: ${{ github.ref_name }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
